### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by pburkholder** [chef-customers/dojo-assessment-guide#13]
Hi,

Can you clarify the license under which this assessment is available? 

The top-level LICENSE  is Hakim's do-anything license, the dojo/LICENSE is Apache 2, but it's not
clear if those licenses apply to the content of the slides as wells as the presentation framework.

Thanks,

Peter

**Comment by irvingpop** [comment]
hey @pburkholder since this project is a clone of reveal.js, we keep the same top-level license.  The DOJO content is Apache 2.0 license, matching all other Chef OSS work.

**Comment by pburkholder** [comment]
Great - thanks for the clarification. Cheers, Peter
