### ISSUE TITLE
outdated warnings

### ISSUE THREAD

**Issue by vinyar** [chef-customers/dojo-assessment-guide#9]
```
...
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
...
```

**Comment by mtyler** [comment]
I'm not seeing these warnings.  What versions of node & npm are you using?

**Comment by vinyar** [comment]
PR here: https://github.com/chef-customers/dojo-assessment-guide/pull/12

**Comment by vinyar** [comment]
npm -versions                      [ruby-2.1.8p440]
{ 'reveal.js': '3.3.0',
  npm: '3.10.3',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.3.1',
  openssl: '1.0.2h',
  uv: '1.9.1',
  v8: '5.0.71.57',
  zlib: '1.2.8' }

---

npm outdated                       [ruby-2.1.8p440]
Package                Current  Wanted  Latest  Location
express                 4.13.4  4.13.4  4.14.0  reveal.js
grunt                    0.4.5   0.4.5   1.0.1  reveal.js
grunt-cli               0.1.13  0.1.13   1.2.0  reveal.js
grunt-contrib-connect   0.11.2  0.11.2   1.0.2  reveal.js
grunt-contrib-cssmin    0.14.0  0.14.0   1.0.1  reveal.js
grunt-contrib-jshint    0.11.3  0.11.3   1.0.0  reveal.js
grunt-contrib-qunit      0.7.0   0.7.0   1.2.0  reveal.js
grunt-contrib-uglify     0.9.2   0.9.2   2.0.0  reveal.js
grunt-contrib-watch      0.6.1   0.6.1   1.0.0  reveal.js
grunt-sass               1.1.0   1.1.0   1.2.0  reveal.js
node-sass                3.7.0   3.7.0   3.8.0  reveal.js
socket.io                1.3.7   1.3.7   1.4.8  reveal.js

**Comment by vinyar** [comment]
new update here: https://github.com/chef-customers/dojo-assessment-guide/issues/14
